### ISSUE TITLE
Question- does it support pk3 files?

### ISSUE THREAD

**Issue by Frisk4973** [thearst3rd/crispy-doom#10]
just wanted to ask

**Comment by thearst3rd** [comment]
I had a small discussion about this in #7 - TLDR is I don't know what .pk3 files are but I can't see anything indicating that Crispy Doom supports them. 

Crispy Doom is not listed: https://doomwiki.org/wiki/PK3
.pk3 support is not mentioned: https://doomwiki.org/wiki/Crispy_Doom
