### ISSUE TITLE
How to load Sigil?

### ISSUE THREAD

**Issue by suparkoro86** [thearst3rd/crispy-doom#5]
Trying to load Sigil wad.  It loads the Sigil title screen but the game starts at E1M1.  Any tips on getting Sigil loaded?

**Comment by thearst3rd** [comment]
I've tested Sigil before, it should work no problem. If you're using the normal wad (`SIGIL_v1_21.wad`), then make sure you're selecting episode 5 rather than episode 1. If you're using the COMPAT wad (`SIGIL_COMPAT_v1_21.wad`), then make sure you're selecting episode 3.

**Comment by thearst3rd** [comment]
Tested it again, seems to work ok :) I loaded `DOOM.WAD` as the main wad and `SIGIL_v1_21.wad` as a pwad, selected episode 5 "SIGIL" and it worked as expected. Let me know if these steps don't work for you, and if so we can reopen the issue.
