### ISSUE TITLE
Is this compatible with megagame.wad?

### ISSUE THREAD

**Issue by Luvar123** [thearst3rd/crispy-doom#9]
Its other wad

**Comment by thearst3rd** [comment]
I can't say I've heard of it. After some searching, it seems the wad is part of this project. Did I find the right one?

https://cutstuff.net/mm8bdm/?page_id=5

The above page says that it uses the Zandronum engine, which is based on ZDoom. If megagame.wad requires ZDoom features, it will not work in Crispy Doom, and by extension it will not work in my Wii U port.

**Comment by Luvar123** [comment]
Yes

**Comment by thearst3rd** [comment]
Ok, then I don't think so. But feel free to try it out. You can test it on the PC version of crispy doom first: https://github.com/fabiangreffrath/crispy-doom/releases/latest

**Comment by Luvar123** [comment]
I'll send you a screenshot in a bit
